### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by wiwalsh** [mgroupntua/LinearAlgebra#12]
**Is your feature request related to a problem? Please describe.**
This seems like a really nice package of linear algebra stuff.  Is it possible to make a nuget package for it?
Also, it seems like the StyleCop has issued... a few warnings.  Need any help cleaning this up?

**Comment by dimtsap** [comment]
@wiwalsh You can already find the nuget version of this package in our own feed. Just use the following link for your nuget config file. _https://pkgs.dev.azure.com/mgroupntua/MSolve/_packaging/MGroup%40Local/nuget/v3/index.json_
